# Generated by Django 4.2.23 on 2025-07-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaps', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swaprequest',
            name='skill',
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='skill_offered_by_sender',
            field=models.CharField(default='N/A', help_text='Skill you will teach in exchange', max_length=255),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='skill_requested_by_sender',
            field=models.CharField(default='N/A', help_text='Skill you want to learn', max_length=255),
        ),
    ]
